測試lhci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,13 +25,8 @@ jobs:
 
     - uses: ./.github/actions/setup-node
 
-    - name: Build
-      run: npm run build
-
-    - name: Lighthouse run
-      run: |
-        npm install -g @lhci/cli@0.3.x
-        lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+    - run: npm install -g @lhci/cli@0.12.x &&
+    - run: npm run build
+    - run: lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
       env:
         LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
-
